-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EXBBDD2025
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EXBBDD2025
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EXBBDD2025` DEFAULT CHARACTER SET utf8 ;
USE `EXBBDD2025` ;

-- -----------------------------------------------------
-- Table `EXBBDD2025`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EXBBDD2025`.`EQUIPO` (
  `CODIGO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CIUDAD` ENUM('MADRID', 'BARCELONA', 'SEVILLA') NULL,
  `AFORO` TINYINT(200) NULL,
  `ANO_FUNDACION` YEAR NULL,
  `NOM_ESTADIO` VARCHAR(45) NULL,
  `NOM_EQUIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXBBDD2025`.`JUGADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EXBBDD2025`.`JUGADOR` (
  `CODIGO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(20) NULL,
  `NACIONALIDAD` ENUM('ESPANOLA', 'BRITANICA', 'PORTUGUESA') NULL,
  `FEC_NAC` DATE NULL,
  `POSICION` ENUM('DEFENSA', 'PORTERO', 'CENTROCAMPISTA') NULL,
  `EQUIPO_CODIGO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CODIGO`, `EQUIPO_CODIGO`),
  INDEX `fk_JUGADOR_EQUIPO1_idx` (`EQUIPO_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_JUGADOR_EQUIPO1`
    FOREIGN KEY (`EQUIPO_CODIGO`)
    REFERENCES `EXBBDD2025`.`EQUIPO` (`CODIGO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXBBDD2025`.`GOL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EXBBDD2025`.`GOL` (
  `MINUTO_GOL` DATETIME NOT NULL,
  `DESCRIPCION` TEXT NULL,
  `JUGADOR_CODIGO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MINUTO_GOL`, `JUGADOR_CODIGO`),
  INDEX `fk_GOL_JUGADOR1_idx` (`JUGADOR_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_GOL_JUGADOR1`
    FOREIGN KEY (`JUGADOR_CODIGO`)
    REFERENCES `EXBBDD2025`.`JUGADOR` (`CODIGO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXBBDD2025`.`PARTIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EXBBDD2025`.`PARTIDO` (
  `CODIGO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NULL,
  `GOL_CASA` VARCHAR(45) NULL,
  `GOL_FUERA` VARCHAR(45) NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXBBDD2025`.`PRESIDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EXBBDD2025`.`PRESIDENTE` (
  `DNI` VARCHAR(9) NOT NULL,
  `NOMBRE` VARCHAR(20) NULL,
  `APELLIDO` VARCHAR(50) NULL,
  `DIREC` VARCHAR(90) NULL,
  `ANO_ELECCION` YEAR NULL,
  `EQUIPO_CODIGO` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_PRESIDENTE_EQUIPO1_idx` (`EQUIPO_CODIGO` ASC) VISIBLE,
  CONSTRAINT `fk_PRESIDENTE_EQUIPO1`
    FOREIGN KEY (`EQUIPO_CODIGO`)
    REFERENCES `EXBBDD2025`.`EQUIPO` (`CODIGO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EXBBDD2025`.`TIENE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EXBBDD2025`.`TIENE` (
  `GOL_MINUTO_GOL` TIME NOT NULL,
  `PARTIDO_CODIGO` INT UNSIGNED NOT NULL,
  `TIPO` VARCHAR(45) NULL,
  PRIMARY KEY (`GOL_MINUTO_GOL`, `PARTIDO_CODIGO`),
  INDEX `fk_GOL_has_PARTIDO_PARTIDO1_idx` (`PARTIDO_CODIGO` ASC) VISIBLE,
  INDEX `fk_GOL_has_PARTIDO_GOL_idx` (`GOL_MINUTO_GOL` ASC) VISIBLE,
  CONSTRAINT `fk_GOL_has_PARTIDO_GOL`
    FOREIGN KEY (`GOL_MINUTO_GOL`)
    REFERENCES `EXBBDD2025`.`GOL` (`MINUTO_GOL`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_GOL_has_PARTIDO_PARTIDO1`
    FOREIGN KEY (`PARTIDO_CODIGO`)
    REFERENCES `EXBBDD2025`.`PARTIDO` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
