-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 7Ejercicio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 7Ejercicio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `7Ejercicio` DEFAULT CHARACTER SET utf8 ;
USE `7Ejercicio` ;

-- -----------------------------------------------------
-- Table `7Ejercicio`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`CLIENTE` (
  `DNI/NIF` VARCHAR(9) NOT NULL,
  `TIPO_CLIENTE` ENUM('A', 'B') NULL,
  `DIRECCION_CL` VARCHAR(100) NULL,
  `LOCALIDAD` VARCHAR(45) NULL,
  `CP` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(300) NULL,
  `NOMBRE_CLIENTE` VARCHAR(20) NULL,
  `APELLIDOS` VARCHAR(40) NULL,
  `CODIGO_POSTAL` VARCHAR(5) NULL,
  PRIMARY KEY (`DNI/NIF`),
  UNIQUE INDEX `NOMBRE_CLIENTE_UNIQUE` (`NOMBRE_CLIENTE` ASC) VISIBLE,
  UNIQUE INDEX `APELLIDOS_UNIQUE` (`APELLIDOS` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`FACTURA` (
  `NºFACTURA` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PAGO` ENUM('EFECTIVO', 'TRANFERENCIA') NULL,
  `IMPORTE` DECIMAL(7,2) NULL,
  `ENVIO` ENUM('DOMICILIO', 'TIENDA') NULL,
  PRIMARY KEY (`NºFACTURA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`DISENO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`DISENO` (
  `idDISEÑO` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FORMATO` ENUM('F1', 'F2', 'F3') NULL,
  `TAMANO_DISENO` SMALLINT NULL,
  `CLIENTE_DNI/NIF` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idDISEÑO`, `CLIENTE_DNI/NIF`),
  INDEX `fk_DISENO_CLIENTE1_idx` (`CLIENTE_DNI/NIF` ASC) VISIBLE,
  CONSTRAINT `fk_DISENO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI/NIF`)
    REFERENCES `7Ejercicio`.`CLIENTE` (`DNI/NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`PRODUCTO` (
  `NOMBRE_PRODUCTO` VARCHAR(45) NOT NULL,
  `DESCRIPCIÓN` TEXT NULL,
  `TAMANO_PRODUCTO` SMALLINT NULL,
  `TIPO_PAPEL` ENUM('A1', 'A2', 'A3') NULL,
  `IMPRESION` TINYINT NULL,
  `ACABADO` ENUM('A1', 'A2') NULL,
  PRIMARY KEY (`NOMBRE_PRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`DEPARTAMENTO` (
  `NOMBRE_DEPARTAMENTO` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(300) NULL,
  PRIMARY KEY (`NOMBRE_DEPARTAMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`EMPLEADO` (
  `DNI` VARCHAR(9) NOT NULL,
  `SEGURIDAD_SOCIAL` VARCHAR(12) NULL,
  `NOMBRE` VARCHAR(20) NULL,
  `APELLIDOS` VARCHAR(90) NULL,
  `EMAIL` VARCHAR(300) NULL,
  `COMISION` TINYINT NULL,
  `SALARIO` DECIMAL(4,2) NULL,
  `DIRECCION_EMP` VARCHAR(100) NULL,
  `DEPARTAMENTO_NOMBRE_DEPARTAMENTO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `fk_EMPLEADO_DEPARTAMENTO1_idx` (`DEPARTAMENTO_NOMBRE_DEPARTAMENTO` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_DEPARTAMENTO1`
    FOREIGN KEY (`DEPARTAMENTO_NOMBRE_DEPARTAMENTO`)
    REFERENCES `7Ejercicio`.`DEPARTAMENTO` (`NOMBRE_DEPARTAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`CLIENTE_TELEFONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`CLIENTE_TELEFONO` (
  `idCLIENTE_TELEFONO` INT NOT NULL,
  `NUMERO_TELEFONO` VARCHAR(9) NULL,
  `CLIENTE_DNI/NIF` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idCLIENTE_TELEFONO`),
  INDEX `fk_CLIENTE_TELEFONO_CLIENTE_idx` (`CLIENTE_DNI/NIF` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_TELEFONO_CLIENTE`
    FOREIGN KEY (`CLIENTE_DNI/NIF`)
    REFERENCES `7Ejercicio`.`CLIENTE` (`DNI/NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`EMPLEADO_TELEFONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`EMPLEADO_TELEFONO` (
  `idEMPLEADO_TELEFONO` INT NOT NULL,
  `NUMERO_TELEFONO` VARCHAR(9) NULL,
  `EMPLEADO_DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idEMPLEADO_TELEFONO`),
  INDEX `fk_EMPLEADO_TELEFONO_EMPLEADO1_idx` (`EMPLEADO_DNI` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_TELEFONO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_DNI`)
    REFERENCES `7Ejercicio`.`EMPLEADO` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`REALIZA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`REALIZA` (
  `PRODUCTO_NOMBRE_PRODUCTO` VARCHAR(45) NOT NULL,
  `EMPLEADO_DNI` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`PRODUCTO_NOMBRE_PRODUCTO`, `EMPLEADO_DNI`),
  INDEX `fk_PRODUCTO_has_EMPLEADO_EMPLEADO1_idx` (`EMPLEADO_DNI` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_EMPLEADO_PRODUCTO1_idx` (`PRODUCTO_NOMBRE_PRODUCTO` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_EMPLEADO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_NOMBRE_PRODUCTO`)
    REFERENCES `7Ejercicio`.`PRODUCTO` (`NOMBRE_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_DNI`)
    REFERENCES `7Ejercicio`.`EMPLEADO` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `7Ejercicio`.`SOLICITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `7Ejercicio`.`SOLICITA` (
  `CLIENTE_DNI/NIF` VARCHAR(9) NOT NULL,
  `PRODUCTO_NOMBRE_PRODUCTO` VARCHAR(45) NOT NULL,
  `FACTURA_NºFACTURA` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`CLIENTE_DNI/NIF`, `PRODUCTO_NOMBRE_PRODUCTO`),
  INDEX `fk_CLIENTE_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_NOMBRE_PRODUCTO` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PRODUCTO_CLIENTE1_idx` (`CLIENTE_DNI/NIF` ASC) VISIBLE,
  INDEX `fk_SOLICITA_FACTURA1_idx` (`FACTURA_NºFACTURA` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_DNI/NIF`)
    REFERENCES `7Ejercicio`.`CLIENTE` (`DNI/NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_NOMBRE_PRODUCTO`)
    REFERENCES `7Ejercicio`.`PRODUCTO` (`NOMBRE_PRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITA_FACTURA1`
    FOREIGN KEY (`FACTURA_NºFACTURA`)
    REFERENCES `7Ejercicio`.`FACTURA` (`NºFACTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
